/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa.ca1;

/**
 *
 * @author taraj
 */
public class AddRouteGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddRouteGUI.class.getName());
    private RouteLinkedList routeList = new RouteLinkedList();
    /**
     * Creates new form AddRouteGUI
     */
    public AddRouteGUI() {
        initComponents();
        //hide extra options as default
        hasRampsCheck.setVisible(false);
        hasLiftsCheck.setVisible(false);
        hasStairsCheck.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRouteGUILabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        routeIDLabel = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        startInput = new javax.swing.JTextField();
        endInput = new javax.swing.JTextField();
        routeIDInput = new javax.swing.JTextField();
        distanceInput = new javax.swing.JTextField();
        walkingRouteCheck = new javax.swing.JCheckBox();
        wheelchairRouteCheck = new javax.swing.JCheckBox();
        hasLiftsCheck = new javax.swing.JCheckBox();
        hasRampsCheck = new javax.swing.JCheckBox();
        hasStairsCheck = new javax.swing.JCheckBox();
        addRouteBack = new javax.swing.JButton();
        addRouteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addRouteGUILabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addRouteGUILabel.setText("Add a new route");

        startLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        startLabel.setText("Starting point:");

        endLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        endLabel.setText("Ending point:");

        routeIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        routeIDLabel.setText("Route name/ID:");

        distanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        distanceLabel.setText("Distance:");

        routeIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeIDInputActionPerformed(evt);
            }
        });

        walkingRouteCheck.setText("Walking route");
        walkingRouteCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkingRouteCheckActionPerformed(evt);
            }
        });

        wheelchairRouteCheck.setText("Wheelchair route");
        wheelchairRouteCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheelchairRouteCheckActionPerformed(evt);
            }
        });

        hasLiftsCheck.setText("Has lifts");

        hasRampsCheck.setText("Has ramps");

        hasStairsCheck.setText("Has stairs");
        hasStairsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasStairsCheckActionPerformed(evt);
            }
        });

        addRouteBack.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        addRouteBack.setText("Go Back");
        addRouteBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteBackActionPerformed(evt);
            }
        });

        addRouteButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        addRouteButton.setText("Add Route");
        addRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRouteGUILabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(distanceLabel)
                            .addComponent(routeIDLabel)
                            .addComponent(endLabel)
                            .addComponent(startLabel))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startInput, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endInput, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(routeIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(distanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(walkingRouteCheck)
                                        .addComponent(hasStairsCheck))
                                    .addGap(100, 100, 100)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wheelchairRouteCheck)
                                        .addComponent(hasRampsCheck)
                                        .addComponent(hasLiftsCheck))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(addRouteBack, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addRouteGUILabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(startLabel))
                                    .addComponent(startInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(endLabel))
                            .addComponent(endInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(routeIDLabel))
                    .addComponent(routeIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(distanceLabel)
                    .addComponent(distanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wheelchairRouteCheck)
                    .addComponent(walkingRouteCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasStairsCheck)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hasRampsCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasLiftsCheck)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRouteBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void routeIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeIDInputActionPerformed

    private void hasStairsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasStairsCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasStairsCheckActionPerformed

    private void addRouteBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteBackActionPerformed
        MenuGUI menuGui = new MenuGUI();
        menuGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addRouteBackActionPerformed

    private void walkingRouteCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkingRouteCheckActionPerformed
        //if walking route checked, show stairs option
        boolean selected = walkingRouteCheck.isSelected();
        hasStairsCheck.setVisible(selected);
        if (!selected) {
            hasStairsCheck.setSelected(false);
        }
    }//GEN-LAST:event_walkingRouteCheckActionPerformed

    private void wheelchairRouteCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelchairRouteCheckActionPerformed
        // show ramp and lifts option if wheelchair route is slected
        boolean selected = wheelchairRouteCheck.isSelected();
        hasRampsCheck.setVisible(selected);
        hasLiftsCheck.setVisible(selected);
        if (!selected) {
            hasRampsCheck.setSelected(false);
            hasLiftsCheck.setSelected(false);
        }
    }//GEN-LAST:event_wheelchairRouteCheckActionPerformed

    private void addRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteButtonActionPerformed
        //accept user input
        String routeID = routeIDInput.getText();
        String start = startInput.getText();
        String end = endInput.getText();
        double distance = Double.parseDouble(distanceInput.getText());
        boolean walkingRoute = walkingRouteCheck.isSelected();
        boolean wheelchairRoute = wheelchairRouteCheck.isSelected();
        
        //create new route object with valurs
        Route newRoute;
        
        //if walking route true (selected)
        if(walkingRoute) {
            boolean hasStairs = hasStairsCheck.isSelected();
            //add new walking route with stairs info
            newRoute = new WalkingRoute (routeID, start, end, distance, hasStairs);
        }
        //if wheelchair route true (selected)
        else if (wheelchairRoute) {
            boolean hasLifts = hasLiftsCheck.isSelected();
            boolean hasRamps = hasRampsCheck.isSelected();
            //add new wheelchair route with ramps and lifts info 
            newRoute = new WheelchairRoute (routeID, start, end, distance, hasLifts, hasRamps);
        }
        //create normal route if none selected
        else {
            newRoute = new Route(routeID, start, end, distance);
        }
        routeList.add(newRoute);
        
        //test
        System.out.println(routeList.printList());

    }//GEN-LAST:event_addRouteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRouteBack;
    private javax.swing.JButton addRouteButton;
    private javax.swing.JLabel addRouteGUILabel;
    private javax.swing.JTextField distanceInput;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JTextField endInput;
    private javax.swing.JLabel endLabel;
    private javax.swing.JCheckBox hasLiftsCheck;
    private javax.swing.JCheckBox hasRampsCheck;
    private javax.swing.JCheckBox hasStairsCheck;
    private javax.swing.JTextField routeIDInput;
    private javax.swing.JLabel routeIDLabel;
    private javax.swing.JTextField startInput;
    private javax.swing.JLabel startLabel;
    private javax.swing.JCheckBox walkingRouteCheck;
    private javax.swing.JCheckBox wheelchairRouteCheck;
    // End of variables declaration//GEN-END:variables
}
