/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa.ca1;

/**
 *
 * @author Tara
 */
public class ObstaclesListGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ObstaclesListGUI.class.getName());
    private ObstaclesQueue obstaclesQueue;
    
    /**
     * Creates new form ObstaclesListGUI
     */
    public ObstaclesListGUI(ObstaclesQueue obstaclesQueue) {
        initComponents();
        this.obstaclesQueue = obstaclesQueue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getObstaclesBtn = new javax.swing.JButton();
        ObstaclesListGUILabel = new javax.swing.JLabel();
        obstaclesBackBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        obstaclesListTextBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getObstaclesBtn.setText("Get obstacles");
        getObstaclesBtn.addActionListener(this::getObstaclesBtnActionPerformed);

        ObstaclesListGUILabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        ObstaclesListGUILabel.setText("Reported Obstacles");

        obstaclesBackBtn.setText("Back");
        obstaclesBackBtn.addActionListener(this::obstaclesBackBtnActionPerformed);

        obstaclesListTextBox.setColumns(20);
        obstaclesListTextBox.setRows(5);
        jScrollPane2.setViewportView(obstaclesListTextBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(getObstaclesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(obstaclesBackBtn)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(ObstaclesListGUILabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {getObstaclesBtn, obstaclesBackBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ObstaclesListGUILabel)
                .addGap(75, 75, 75)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obstaclesBackBtn)
                    .addComponent(getObstaclesBtn))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getObstaclesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getObstaclesBtnActionPerformed
        obstaclesListTextBox.setText(obstaclesQueue.printQ());
    }//GEN-LAST:event_getObstaclesBtnActionPerformed

    private void obstaclesBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obstaclesBackBtnActionPerformed
        MenuGUI menuGui = new MenuGUI();
        menuGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_obstaclesBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ObstaclesListGUILabel;
    private javax.swing.JButton getObstaclesBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton obstaclesBackBtn;
    private javax.swing.JTextArea obstaclesListTextBox;
    // End of variables declaration//GEN-END:variables
}
