/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa.ca1;

/**
 *
 * @author Tara
 */
public class ObstaclesListGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ObstaclesListGUI.class.getName());
    private ObstaclesQueue obstaclesQueue;
    
    
    /**
     * Creates new form ObstaclesListGUI
     */
    public ObstaclesListGUI(ObstaclesQueue obstaclesQueue) {    
        initComponents();
        this.obstaclesQueue = obstaclesQueue;
        successLabel.setVisible(false);
        obstaclesListTextBox.setText(obstaclesQueue.printQ());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshObstaclesBtn = new javax.swing.JButton();
        ObstaclesListGUILabel = new javax.swing.JLabel();
        obstaclesBackBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        obstaclesListTextBox = new javax.swing.JTextArea();
        delObstacleInput = new javax.swing.JTextField();
        delObstacleBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        successLabel = new javax.swing.JLabel();
        updateObstacleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        refreshObstaclesBtn.setText("Refresh");
        refreshObstaclesBtn.addActionListener(this::refreshObstaclesBtnActionPerformed);

        ObstaclesListGUILabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        ObstaclesListGUILabel.setText("Reported Obstacles");

        obstaclesBackBtn.setText("Back");
        obstaclesBackBtn.addActionListener(this::obstaclesBackBtnActionPerformed);

        obstaclesListTextBox.setColumns(20);
        obstaclesListTextBox.setRows(5);
        jScrollPane2.setViewportView(obstaclesListTextBox);

        delObstacleBtn.setText("Delete Obstacle");
        delObstacleBtn.addActionListener(this::delObstacleBtnActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please enter the routeID of the obstacle you would like to delete:");

        successLabel.setForeground(new java.awt.Color(204, 0, 0));
        successLabel.setText("Successfully deleted!");

        updateObstacleBtn.setText("Update an obstacle");
        updateObstacleBtn.addActionListener(this::updateObstacleBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(ObstaclesListGUILabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshObstaclesBtn)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(updateObstacleBtn)
                        .addGap(18, 18, 18)
                        .addComponent(obstaclesBackBtn))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delObstacleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delObstacleInput)))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(successLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {obstaclesBackBtn, refreshObstaclesBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ObstaclesListGUILabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshObstaclesBtn)
                    .addComponent(obstaclesBackBtn)
                    .addComponent(updateObstacleBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delObstacleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delObstacleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(successLabel)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshObstaclesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshObstaclesBtnActionPerformed
        obstaclesListTextBox.setText(obstaclesQueue.printQ());
        //hide success label when get obstacles (refresh) is clicked
        successLabel.setVisible(false);

    }//GEN-LAST:event_refreshObstaclesBtnActionPerformed

    private void obstaclesBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obstaclesBackBtnActionPerformed
        MenuGUI menuGui = new MenuGUI();
        menuGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_obstaclesBackBtnActionPerformed

    private void delObstacleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delObstacleBtnActionPerformed
        String delete = delObstacleInput.getText().trim().toLowerCase();
        obstaclesQueue.dequeue(delete);
        successLabel.setVisible(true);
        //refresh the text box
        obstaclesListTextBox.setText(obstaclesQueue.printQ());
    }//GEN-LAST:event_delObstacleBtnActionPerformed

    private void updateObstacleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateObstacleBtnActionPerformed
        UpdateObstacleGUI updateGUI = new UpdateObstacleGUI(obstaclesQueue);
        updateGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateObstacleBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ObstaclesListGUILabel;
    private javax.swing.JButton delObstacleBtn;
    private javax.swing.JTextField delObstacleInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton obstaclesBackBtn;
    private javax.swing.JTextArea obstaclesListTextBox;
    private javax.swing.JButton refreshObstaclesBtn;
    private javax.swing.JLabel successLabel;
    private javax.swing.JButton updateObstacleBtn;
    // End of variables declaration//GEN-END:variables
}
