/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa.ca1;

/**
 *
 * @author taraj
 */
public class RecentRoutesGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecentRoutesGUI.class.getName());
    private RouteLinkedList routes;
    /**
     * Creates new form RecentRoutesGUI
     */
    public RecentRoutesGUI(RouteLinkedList routes) {
        initComponents();
        this.routes = routes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SavedRoutesGUILabel = new javax.swing.JLabel();
        savedBackBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        recentRoutesTextBox = new javax.swing.JTextArea();
        getRoutesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SavedRoutesGUILabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SavedRoutesGUILabel.setText("Recent routes");

        savedBackBtn.setText("Back");
        savedBackBtn.addActionListener(this::savedBackBtnActionPerformed);

        recentRoutesTextBox.setColumns(20);
        recentRoutesTextBox.setRows(5);
        jScrollPane2.setViewportView(recentRoutesTextBox);

        getRoutesBtn.setText("Get routes");
        getRoutesBtn.addActionListener(this::getRoutesBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SavedRoutesGUILabel)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(getRoutesBtn)
                        .addGap(40, 40, 40)
                        .addComponent(savedBackBtn)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(SavedRoutesGUILabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savedBackBtn)
                    .addComponent(getRoutesBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savedBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedBackBtnActionPerformed
        MenuGUI menuGui = new MenuGUI();
        menuGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_savedBackBtnActionPerformed

    private void getRoutesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRoutesBtnActionPerformed
        recentRoutesTextBox.setText(routes.printList());
    }//GEN-LAST:event_getRoutesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SavedRoutesGUILabel;
    private javax.swing.JButton getRoutesBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea recentRoutesTextBox;
    private javax.swing.JButton savedBackBtn;
    // End of variables declaration//GEN-END:variables
}
