/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa.ca1;

/**
 *
 * @author taraj
 */
public class ReportGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportGUI.class.getName());
    private ObstaclesQueue obstaclesQueue;
    
    /**
     * Creates new form ReportGUI
     */
    public ReportGUI(ObstaclesQueue obstaclesQueue) {
        this.obstaclesQueue = obstaclesQueue;
        initComponents();
        //hide extra options
        walkingBarriers.setVisible(false);
        wheelchairBarriers.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportWalkRadio = new javax.swing.ButtonGroup();
        reportWheelchairRadio = new javax.swing.ButtonGroup();
        typeOfBarrier = new javax.swing.ButtonGroup();
        reportGUILabel = new javax.swing.JLabel();
        walkingBarrierSelected = new javax.swing.JRadioButton();
        wheelchairBarrierSelected = new javax.swing.JRadioButton();
        locationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        barrierLocationInput = new javax.swing.JTextPane();
        reportObstacleBtn = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionInput = new javax.swing.JTextPane();
        routeIDBarrierLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        routeIDInput = new javax.swing.JTextPane();
        walkingBarriers = new javax.swing.JLayeredPane();
        walkingWeather = new javax.swing.JRadioButton();
        walkingSteepPath = new javax.swing.JRadioButton();
        walkingTrafficHazard = new javax.swing.JRadioButton();
        walkingPhysicalObstruction = new javax.swing.JRadioButton();
        barrierBackBtn = new javax.swing.JButton();
        wheelchairBarriers = new javax.swing.JLayeredPane();
        noLift = new javax.swing.JRadioButton();
        noRamp = new javax.swing.JRadioButton();
        narrowCorridors = new javax.swing.JRadioButton();
        badSurfacee = new javax.swing.JRadioButton();
        physicalObstruction = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reportGUILabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        reportGUILabel.setText("Report barriers or obstacles");

        typeOfBarrier.add(walkingBarrierSelected);
        walkingBarrierSelected.setText("Walking barrier");
        walkingBarrierSelected.addActionListener(this::walkingBarrierSelectedActionPerformed);

        typeOfBarrier.add(wheelchairBarrierSelected);
        wheelchairBarrierSelected.setText("Wheelchair Barrier");
        wheelchairBarrierSelected.addActionListener(this::wheelchairBarrierSelectedActionPerformed);

        locationLabel.setText("Location:");

        jScrollPane1.setViewportView(barrierLocationInput);

        reportObstacleBtn.setText("Report Obstacle");
        reportObstacleBtn.addActionListener(this::reportObstacleBtnActionPerformed);

        descriptionLabel.setText("Description:");

        jScrollPane2.setViewportView(descriptionInput);

        routeIDBarrierLabel.setText("Route ID (Optional)");

        jScrollPane3.setViewportView(routeIDInput);

        reportWalkRadio.add(walkingWeather);
        walkingWeather.setText("Weather conditions");

        reportWalkRadio.add(walkingSteepPath);
        walkingSteepPath.setText("Steep or difficult path");

        reportWalkRadio.add(walkingTrafficHazard);
        walkingTrafficHazard.setText("Traffic hazard");

        reportWalkRadio.add(walkingPhysicalObstruction);
        walkingPhysicalObstruction.setText("Physical obstruction");

        walkingBarriers.setLayer(walkingWeather, javax.swing.JLayeredPane.DEFAULT_LAYER);
        walkingBarriers.setLayer(walkingSteepPath, javax.swing.JLayeredPane.DEFAULT_LAYER);
        walkingBarriers.setLayer(walkingTrafficHazard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        walkingBarriers.setLayer(walkingPhysicalObstruction, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout walkingBarriersLayout = new javax.swing.GroupLayout(walkingBarriers);
        walkingBarriers.setLayout(walkingBarriersLayout);
        walkingBarriersLayout.setHorizontalGroup(
            walkingBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, walkingBarriersLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(walkingBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walkingTrafficHazard)
                    .addComponent(walkingWeather)
                    .addComponent(walkingSteepPath)
                    .addComponent(walkingPhysicalObstruction)))
        );
        walkingBarriersLayout.setVerticalGroup(
            walkingBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walkingBarriersLayout.createSequentialGroup()
                .addComponent(walkingPhysicalObstruction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walkingSteepPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walkingWeather)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walkingTrafficHazard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barrierBackBtn.setText("Go Back");
        barrierBackBtn.addActionListener(this::barrierBackBtnActionPerformed);

        reportWheelchairRadio.add(noLift);
        noLift.setText("No lift");
        noLift.addActionListener(this::noLiftActionPerformed);

        reportWheelchairRadio.add(noRamp);
        noRamp.setText("No ramp");

        reportWheelchairRadio.add(narrowCorridors);
        narrowCorridors.setText("Narrow corridors or doors");

        reportWheelchairRadio.add(badSurfacee);
        badSurfacee.setText("Bad surface");

        reportWheelchairRadio.add(physicalObstruction);
        physicalObstruction.setText("Physical obstruction");
        physicalObstruction.addActionListener(this::physicalObstructionActionPerformed);

        wheelchairBarriers.setLayer(noLift, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(noRamp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(narrowCorridors, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(badSurfacee, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(physicalObstruction, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout wheelchairBarriersLayout = new javax.swing.GroupLayout(wheelchairBarriers);
        wheelchairBarriers.setLayout(wheelchairBarriersLayout);
        wheelchairBarriersLayout.setHorizontalGroup(
            wheelchairBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheelchairBarriersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wheelchairBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wheelchairBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(noLift, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(badSurfacee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(narrowCorridors, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(physicalObstruction, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(noRamp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wheelchairBarriersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {badSurfacee, narrowCorridors, noLift, noRamp, physicalObstruction});

        wheelchairBarriersLayout.setVerticalGroup(
            wheelchairBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheelchairBarriersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noRamp, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noLift, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badSurfacee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(narrowCorridors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(physicalObstruction)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(routeIDBarrierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(locationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(reportGUILabel)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(walkingBarriers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barrierBackBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(walkingBarrierSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportObstacleBtn)
                    .addComponent(wheelchairBarriers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wheelchairBarrierSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {barrierBackBtn, reportObstacleBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(reportGUILabel)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(routeIDBarrierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wheelchairBarrierSelected)
                    .addComponent(walkingBarrierSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(walkingBarriers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wheelchairBarriers)
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportObstacleBtn)
                    .addComponent(barrierBackBtn))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wheelchairBarrierSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelchairBarrierSelectedActionPerformed
        boolean selected = wheelchairBarrierSelected.isSelected();
        //show options if wheelchair barrier is selected
        wheelchairBarriers.setVisible(selected);
        //hide walking options
        walkingBarriers.setVisible(false);
        //deselect walking subtypes if wheelchair is selected
        reportWalkRadio.clearSelection();
        

    }//GEN-LAST:event_wheelchairBarrierSelectedActionPerformed

    private void walkingBarrierSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkingBarrierSelectedActionPerformed
        boolean selected = walkingBarrierSelected.isSelected();
        //show options if walking barrier is selected
        walkingBarriers.setVisible(selected);
        //hide wheelchair options
        wheelchairBarriers.setVisible(false);
        //deselect subtypes for wheelchair if walking barrier selected
        reportWheelchairRadio.clearSelection();
    }//GEN-LAST:event_walkingBarrierSelectedActionPerformed

    private void barrierBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrierBackBtnActionPerformed
        MenuGUI menuGui = new MenuGUI();
        menuGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_barrierBackBtnActionPerformed

    private void reportObstacleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportObstacleBtnActionPerformed
        String location = barrierLocationInput.getText();
        String description = descriptionInput.getText();
        String routeID = routeIDInput.getText();
        String barrierType = "";
        String subType = "";
        //if its a walking barrier
        if (walkingBarrierSelected.isSelected()) {
            barrierType = "Walking";
            //check type of obstruction and set subType 
            if (walkingPhysicalObstruction.isSelected()) {
                subType = "Physical obstruction";
            } else if (walkingSteepPath.isSelected()) {
                subType = "Steep or difficult path";
            } else if (walkingWeather.isSelected()) {
                subType = "Weather conditions";
            } else if (walkingTrafficHazard.isSelected()) {
                subType = "Traffic hazard";
            }
        //if its a wheelchair barrier
        } else if (wheelchairBarrierSelected.isSelected()) {
            barrierType = "Wheelchair";
            //check type and set subtype
            if (noRamp.isSelected()) {
                subType = "No ramp";
            } else if (noLift.isSelected()) {
                subType = "No lift";
            } else if (badSurfacee.isSelected()) {
                subType = "Bad surface";
            } else if (narrowCorridors.isSelected()) {
                subType = "Narrow corridors";
            } else if (physicalObstruction.isSelected()) {
                subType = "Physical obstruction";
            }
        }
        //set newObstacle object 
        Obstacles newObstacle = new Obstacles(location, description, routeID, barrierType, subType);
        //add newobstacle to queie 
        obstaclesQueue.enqueue(newObstacle);
        
        
    }//GEN-LAST:event_reportObstacleBtnActionPerformed

    private void physicalObstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalObstructionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicalObstructionActionPerformed

    private void noLiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noLiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noLiftActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton badSurfacee;
    private javax.swing.JButton barrierBackBtn;
    private javax.swing.JTextPane barrierLocationInput;
    private javax.swing.JTextPane descriptionInput;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JRadioButton narrowCorridors;
    private javax.swing.JRadioButton noLift;
    private javax.swing.JRadioButton noRamp;
    private javax.swing.JRadioButton physicalObstruction;
    private javax.swing.JLabel reportGUILabel;
    private javax.swing.JButton reportObstacleBtn;
    private javax.swing.ButtonGroup reportWalkRadio;
    private javax.swing.ButtonGroup reportWheelchairRadio;
    private javax.swing.JLabel routeIDBarrierLabel;
    private javax.swing.JTextPane routeIDInput;
    private javax.swing.ButtonGroup typeOfBarrier;
    private javax.swing.JRadioButton walkingBarrierSelected;
    private javax.swing.JLayeredPane walkingBarriers;
    private javax.swing.JRadioButton walkingPhysicalObstruction;
    private javax.swing.JRadioButton walkingSteepPath;
    private javax.swing.JRadioButton walkingTrafficHazard;
    private javax.swing.JRadioButton walkingWeather;
    private javax.swing.JRadioButton wheelchairBarrierSelected;
    private javax.swing.JLayeredPane wheelchairBarriers;
    // End of variables declaration//GEN-END:variables
}
