/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa.ca1;

/**
 *
 * @author taraj
 */
public class ReportGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportGUI.class.getName());

    /**
     * Creates new form ReportGUI
     */
    public ReportGUI() {
        initComponents();
        //hide extra options
        walkingBarriers.setVisible(false);
        wheelchairBarriers.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportWalkRadio = new javax.swing.ButtonGroup();
        reportWheelchairRadio = new javax.swing.ButtonGroup();
        reportGUILabel = new javax.swing.JLabel();
        walkingBarrierSelected = new javax.swing.JRadioButton();
        wheelchairBarrierSelected = new javax.swing.JRadioButton();
        locationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        barrierLocationInput = new javax.swing.JTextPane();
        reportObstacleBtn = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionInput = new javax.swing.JTextPane();
        routeIDBarrierLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionInput1 = new javax.swing.JTextPane();
        walkingBarriers = new javax.swing.JLayeredPane();
        walkingWeather = new javax.swing.JRadioButton();
        walkingSteepPath = new javax.swing.JRadioButton();
        walkingTrafficHazard = new javax.swing.JRadioButton();
        walkingPhysicalObstruction = new javax.swing.JRadioButton();
        wheelchairBarriers = new javax.swing.JLayeredPane();
        noLift = new javax.swing.JRadioButton();
        narrowCorridors = new javax.swing.JRadioButton();
        badSurfacee = new javax.swing.JRadioButton();
        physicalObstruction = new javax.swing.JRadioButton();
        noRamp = new javax.swing.JRadioButton();
        barrierBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reportGUILabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportGUILabel.setText("Report barriers or obstacles");

        walkingBarrierSelected.setText("Walking barrier");
        walkingBarrierSelected.addActionListener(this::walkingBarrierSelectedActionPerformed);

        wheelchairBarrierSelected.setText("Wheelchair Barrier");
        wheelchairBarrierSelected.addActionListener(this::wheelchairBarrierSelectedActionPerformed);

        locationLabel.setText("Location:");

        jScrollPane1.setViewportView(barrierLocationInput);

        reportObstacleBtn.setText("Report Obstacle");

        descriptionLabel.setText("Description:");

        jScrollPane2.setViewportView(descriptionInput);

        routeIDBarrierLabel.setText("Route ID (Optional)");

        jScrollPane3.setViewportView(descriptionInput1);

        reportWalkRadio.add(walkingWeather);
        walkingWeather.setText("Weather conditions");

        reportWalkRadio.add(walkingSteepPath);
        walkingSteepPath.setText("Steep or difficult path");

        reportWalkRadio.add(walkingTrafficHazard);
        walkingTrafficHazard.setText("Traffic hazard");

        reportWalkRadio.add(walkingPhysicalObstruction);
        walkingPhysicalObstruction.setText("Physical obstruction");

        walkingBarriers.setLayer(walkingWeather, javax.swing.JLayeredPane.DEFAULT_LAYER);
        walkingBarriers.setLayer(walkingSteepPath, javax.swing.JLayeredPane.DEFAULT_LAYER);
        walkingBarriers.setLayer(walkingTrafficHazard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        walkingBarriers.setLayer(walkingPhysicalObstruction, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout walkingBarriersLayout = new javax.swing.GroupLayout(walkingBarriers);
        walkingBarriers.setLayout(walkingBarriersLayout);
        walkingBarriersLayout.setHorizontalGroup(
            walkingBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walkingBarriersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(walkingBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walkingSteepPath)
                    .addComponent(walkingPhysicalObstruction)
                    .addComponent(walkingWeather)
                    .addComponent(walkingTrafficHazard))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        walkingBarriersLayout.setVerticalGroup(
            walkingBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walkingBarriersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(walkingPhysicalObstruction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walkingSteepPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walkingWeather)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walkingTrafficHazard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reportWheelchairRadio.add(noLift);
        noLift.setText("No lift");
        noLift.addActionListener(this::noLiftActionPerformed);

        reportWheelchairRadio.add(narrowCorridors);
        narrowCorridors.setText("Narrow corridors or doors");

        reportWheelchairRadio.add(badSurfacee);
        badSurfacee.setText("Bad surface");

        reportWheelchairRadio.add(physicalObstruction);
        physicalObstruction.setText("Physical obstruction");

        reportWheelchairRadio.add(noRamp);
        noRamp.setText("No ramp");

        wheelchairBarriers.setLayer(noLift, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(narrowCorridors, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(badSurfacee, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(physicalObstruction, javax.swing.JLayeredPane.DEFAULT_LAYER);
        wheelchairBarriers.setLayer(noRamp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout wheelchairBarriersLayout = new javax.swing.GroupLayout(wheelchairBarriers);
        wheelchairBarriers.setLayout(wheelchairBarriersLayout);
        wheelchairBarriersLayout.setHorizontalGroup(
            wheelchairBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheelchairBarriersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wheelchairBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noRamp)
                    .addComponent(noLift, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badSurfacee, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(narrowCorridors)
                    .addComponent(physicalObstruction))
                .addContainerGap())
        );
        wheelchairBarriersLayout.setVerticalGroup(
            wheelchairBarriersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheelchairBarriersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noRamp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noLift)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badSurfacee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(narrowCorridors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(physicalObstruction)
                .addContainerGap())
        );

        barrierBackBtn.setText("Go Back");
        barrierBackBtn.addActionListener(this::barrierBackBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(reportGUILabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(routeIDBarrierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(locationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(walkingBarrierSelected)
                                    .addComponent(walkingBarriers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barrierBackBtn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wheelchairBarriers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wheelchairBarrierSelected)
                                    .addComponent(reportObstacleBtn))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(reportGUILabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(locationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(routeIDBarrierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wheelchairBarrierSelected)
                    .addComponent(walkingBarrierSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wheelchairBarriers)
                    .addComponent(walkingBarriers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportObstacleBtn)
                    .addComponent(barrierBackBtn))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wheelchairBarrierSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelchairBarrierSelectedActionPerformed
        boolean selected = wheelchairBarrierSelected.isSelected();
        //show options if wheelchair barrier is selected
        wheelchairBarriers.setVisible(selected);
        
    }//GEN-LAST:event_wheelchairBarrierSelectedActionPerformed

    private void walkingBarrierSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkingBarrierSelectedActionPerformed
        boolean selected = walkingBarrierSelected.isSelected();
        //show options if walking barrier is selected
        walkingBarriers.setVisible(selected);
    }//GEN-LAST:event_walkingBarrierSelectedActionPerformed

    private void noLiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noLiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noLiftActionPerformed

    private void barrierBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrierBackBtnActionPerformed
        MenuGUI menuGui = new MenuGUI();
        menuGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_barrierBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton badSurfacee;
    private javax.swing.JButton barrierBackBtn;
    private javax.swing.JTextPane barrierLocationInput;
    private javax.swing.JTextPane descriptionInput;
    private javax.swing.JTextPane descriptionInput1;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JRadioButton narrowCorridors;
    private javax.swing.JRadioButton noLift;
    private javax.swing.JRadioButton noRamp;
    private javax.swing.JRadioButton physicalObstruction;
    private javax.swing.JLabel reportGUILabel;
    private javax.swing.JButton reportObstacleBtn;
    private javax.swing.ButtonGroup reportWalkRadio;
    private javax.swing.ButtonGroup reportWheelchairRadio;
    private javax.swing.JLabel routeIDBarrierLabel;
    private javax.swing.JRadioButton walkingBarrierSelected;
    private javax.swing.JLayeredPane walkingBarriers;
    private javax.swing.JRadioButton walkingPhysicalObstruction;
    private javax.swing.JRadioButton walkingSteepPath;
    private javax.swing.JRadioButton walkingTrafficHazard;
    private javax.swing.JRadioButton walkingWeather;
    private javax.swing.JRadioButton wheelchairBarrierSelected;
    private javax.swing.JLayeredPane wheelchairBarriers;
    // End of variables declaration//GEN-END:variables
}
